In [6]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

from torch.utils.data import DataLoader, TensorDataset

import torch.optim as optim
from sklearn.model_selection import train_test_split
import mlflow
from mlflow.models.signature import infer_signature

from tqdm import tqdm

from faiss import write_index, read_index

import warnings
warnings.filterwarnings('ignore')

In [7]:
pd.set_option('display.max_colwidth', None)

In [7]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [8]:
files = ['product_brand_embedding.npy', 'product_bullet_point_embedding.npy', 'product_color_embedding.npy', 'product_title_embedding.npy', 'product_description_embedding.npy', 'query_embedding.npy']

data = []
for file in files:
    data.append(np.load(f'../data/new_embeddings/{file}'))

In [9]:
embedding = np.concat((data[0],data[1],data[2],data[3],data[4],data[5]),axis=1)

In [10]:
labels = pd.read_csv(f'../data/data.csv')['binary_label'].values

In [11]:
embedding.shape

(99909, 4608)

In [12]:
labels.shape

(99909,)

In [13]:
x_train, x_test, y_train, y_test = train_test_split(embedding, labels, test_size=0.2, random_state=42, shuffle=True)

In [14]:
x_train = torch.from_numpy(x_train)
x_test = torch.from_numpy(x_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [15]:
product_idx = 3840

In [16]:
# query_embeddings = x_train[:79904,product_idx:]
# product_embeddings = x_train[:79904,:product_idx]

In [17]:
torch.rand(768,32).reshape(32,768).shape

torch.Size([32, 768])

In [18]:
class QueryTower(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(QueryTower, self).__init__()
        self.query_tower = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Linear(256, output_dim)
        )
    
    def forward(self, query_input):
        query_input = query_input.float()
        query_input = query_input.view(-1,768)
        query_emb = self.query_tower(query_input)
        query_emb = nn.functional.normalize(query_emb, p=2, dim=1)
        
        return query_emb

In [19]:
class ProductTower(nn.Module):    
    def __init__(self, input_dim, output_dim):
        super(ProductTower, self).__init__()
        self.product_tower = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.ReLU(),
            nn.Linear(256, output_dim)
        )
    
    def forward(self, product_input):
        product_input = product_input.float()
        product_input = product_input.view(-1,3840)
        product_emb = self.product_tower(product_input)
        product_emb = nn.functional.normalize(product_emb, p=2, dim=1)
    
        return product_emb

In [20]:
class ContrastiveLoss(nn.Module):
    def __init__(self, margin=1.0):
        super(ContrastiveLoss, self).__init__()
        self.margin = margin

    def forward(self, query_emb, pos_product_emb, neg_product_emb):
        pos_dist = torch.norm(query_emb - pos_product_emb, p=2, dim=1)
        neg_dist = torch.norm(query_emb - neg_product_emb, p=2, dim=1)
        # print(pos_dist.shape, neg_dist.shape)
        loss = torch.mean(torch.relu(pos_dist - neg_dist + self.margin))
        # print(loss)
        return loss

In [21]:
query_dim = 768
product_dim = 3840

output_dim = 32
batch_size = 32

train_size = x_train.shape[0] - (x_train.shape[0] % 32)
num_epochs = 100
test_size = x_test.shape[0] - (x_test.shape[0] % 32)

train_num_batches = int(train_size/batch_size)
test_num_batches = int(test_size/batch_size)

query_model = QueryTower(query_dim, output_dim).to(device)
product_model = ProductTower(product_dim, output_dim).to(device)
optimizer = optim.Adam(list(query_model.parameters()) + list(product_model.parameters()), lr=0.001)
criterion = ContrastiveLoss()

train_dataset = TensorDataset(x_train[:train_size,product_idx:], x_train[:train_size,:product_idx])
train_dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

test_dataset = TensorDataset(x_test[:test_size,product_idx:], x_test[:test_size,:product_idx])
test_dataloader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True)

In [18]:
train_size

79904

In [22]:
mlflow.set_tracking_uri(uri='http://127.0.0.1:5000')
mlflow.start_run()
mlflow.log_param("epochs", num_epochs)

loss = 0

# Training loop
for epoch in tqdm(range(num_epochs)):    

    query_model.train()
    product_model.train()
    train_batch_loss = 0

    for query_batch, pos_product_batch in train_dataloader:

        query_batch = query_batch.to(device)
        pos_product_batch = pos_product_batch.to(device)

        # Negative sampling: shuffle product embeddings
        neg_product_batch = x_train[:train_size,:product_idx][torch.randperm(train_size)[:batch_size]]
        neg_product_batch = neg_product_batch.to(device)

        # print(query_batch.shape, pos_product_batch.shape, neg_product_batch.shape)

        # Forward pass
        query_emb = query_model(query_batch)
        pos_product_emb = product_model(pos_product_batch)
        neg_product_emb = product_model(neg_product_batch)

        # print(query_emb.shape, pos_product_emb.shape, neg_product_emb.shape)
        # Compute loss
        train_batch_loss = criterion(query_emb, pos_product_emb, neg_product_emb)

        # Backpropagation
        optimizer.zero_grad()
        train_batch_loss.backward()
        optimizer.step()

        train_batch_loss += train_batch_loss

    total_train_loss = train_batch_loss/train_num_batches

    query_model.eval()
    product_model.eval()

    test_batch_loss = 0
    with torch.no_grad():
        for query_batch, product_batch in test_dataloader:

            query_batch = query_batch.to(device)
            product_batch = product_batch.to(device)


            neg_product_batch = x_test[:test_size,:product_idx][torch.randperm(test_size)[:batch_size]]
            neg_product_batch = neg_product_batch.to(device)
            
            # print(query_batch.shape, product_batch.shape, neg_product_batch.shape)
            query_emb = query_model(query_batch)
            pos_product_emb = product_model(pos_product_batch)
            neg_product_emb = product_model(neg_product_batch)

            test_batch_loss = criterion(query_emb, pos_product_emb, neg_product_emb)

            test_batch_loss += test_batch_loss

    total_test_loss = test_batch_loss/test_num_batches

    if (epoch+1) % 10 == 0:    
        print(f"Epoch {epoch+1}/{num_epochs}, Train Loss: {total_train_loss:.4f}, Test Loss: {total_test_loss:.4f}")


mlflow.log_metric("Average Loss", total_test_loss)
mlflow.pytorch.log_model(product_model, 'Product Tower',registered_model_name='product_tower')
mlflow.pytorch.log_model(query_model, 'Query Tower',registered_model_name='query_tower')

mlflow.end_run()

 10%|█         | 10/100 [02:06<18:36, 12.40s/it]

Epoch 10/100, Train Loss: 0.0001, Test Loss: 0.0032

 20%|██        | 20/100 [04:02<14:25, 10.82s/it]

Epoch 20/100, Train Loss: 0.0001, Test Loss: 0.0030

 30%|███       | 30/100 [06:13<15:33, 13.34s/it]

Epoch 30/100, Train Loss: 0.0001, Test Loss: 0.0031

 40%|████      | 40/100 [08:27<13:30, 13.52s/it]

Epoch 40/100, Train Loss: 0.0001, Test Loss: 0.0031

 50%|█████     | 50/100 [10:34<10:17, 12.35s/it]

Epoch 50/100, Train Loss: 0.0001, Test Loss: 0.0033

 60%|██████    | 60/100 [12:42<08:32, 12.81s/it]

Epoch 60/100, Train Loss: 0.0001, Test Loss: 0.0032

 70%|███████   | 70/100 [14:35<05:21, 10.72s/it]

Epoch 70/100, Train Loss: 0.0001, Test Loss: 0.0033

 80%|████████  | 80/100 [16:42<04:29, 13.47s/it]

Epoch 80/100, Train Loss: 0.0001, Test Loss: 0.0029

 90%|█████████ | 90/100 [18:58<02:16, 13.63s/it]

Epoch 90/100, Train Loss: 0.0001, Test Loss: 0.0030

100%|██████████| 100/100 [21:07<00:00, 12.68s/it]

Epoch 100/100, Train Loss: 0.0000, Test Loss: 0.0033

2025/04/04 11:07:29 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Registered model 'product_tower' already exists. Creating a new version of this model...
2025/04/04 11:07:29 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: product_tower, version 2
Created version '2' of model 'product_tower'.
2025/04/04 11:07:32 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
Registered model 'query_tower' already exists. Creating a new version of this model...
2025/04/04 11:07:32 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: query_tower, version 10

🏃 View run nimble-gnat-824 at: http://127.0.0.1:5000/#/experiments/0/runs/4b210c961b6a4d5996219ea5e5dfc64f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/0

Created version '10' of model 'query_tower'.

In [23]:
embedding = torch.from_numpy(embedding)

In [24]:
import faiss

product_model.eval()
with torch.no_grad():
    product_embeddings_faiss = product_model(embedding[:,:3840].to(device))

In [25]:
index = faiss.IndexFlatL2(32)

index.add(product_embeddings_faiss.cpu().numpy())

In [ ]:

write_index(index, "../assets/product_tower_embedding.index")

In [6]:
index = read_index("../assets/product_tower_embedding.index")

In [37]:
def retrieve_products(query, top_k=5):
    query_emb = query_model(query.to(device))
    query_emb_np = query_emb.cpu().detach().numpy()
    
    _, indices = index.search(query_emb_np, top_k) 
    return indices

In [11]:
df = pd.read_csv('../data/data.csv')

In [10]:
df.columns

Index(['product_id', 'product_title', 'product_description',
       'product_bullet_point', 'product_brand', 'product_color', 'query',
       'esci_label', 'split', 'binary_label'],
      dtype='object')

In [14]:
df.iloc[848]

product_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         B071LN6Q9Y
product_title                                                                                                                                                                                                                                                                                                                                                                                                                                          hangman products elephant hook ceiling hanger  white pack of 5 hangers
product_description     elegant easy and now for indoors or outdoors the elephant hook ceiling hook installs in under a minute no drilling or pilot hole necessary simply screw in the selfdrilling doubleheaded bear claw hanger a special coating protects the steel in any outdoor conditions snap the elephant hook in place over the exposed collar swivel to desired angle and allow the weight of your item to lock into place comes in three finishes to match decor holds 100 lbs in wood 30 lbs in drywall patented
product_bullet_point                                                                                                                                                                                                                                                           5 white elephant hooks\neasy to use ceiling hook installs directly into wood stud or into drywall with supplied anchor\nswivels 360  corrosion resistant  patented\nholds 20lbs in drywall 100lbs in wood\nintended for outdoor and indoor use
product_brand                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         hangman
product_color                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           white
query                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          soffit hangers
esci_label                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  S
split                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   train
binary_label                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0
Name: 848, dtype: object

In [3]:
from sentence_transformers import SentenceTransformer

emb_model = SentenceTransformer('../assets/gte-multilingual-base',trust_remote_code=True)

Some weights of the model checkpoint at ../assets/gte-multilingual-base were not used when initializing NewModel: {'classifier.weight', 'classifier.bias'}
- This IS expected if you are initializing NewModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing NewModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [7]:
def get_embeddings(text):
    embeddings = emb_model.encode(text, normalize_embeddings=False, show_progress_bar=True)
    return embeddings.squeeze()

In [29]:
emb_example = torch.from_numpy(get_embeddings(df.iloc[100].to_list()[1:7]))

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [30]:
emb_example = emb_example.reshape((1,4608))

In [ ]:
new_query = emb_example[:,product_idx:]
product = emb_example[:,:product_idx]

In [ ]:
recommended_products = retrieve_products(new_query, top_k=5)
print("Recommended Product Indices:", recommended_products)

Recommended Product Indices: [[28094   100 51588 23565 50833]]

In [39]:
recommended_products[0]

array([28094,   100, 51588, 23565, 50833])

In [40]:
df.iloc[100]

product_id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  B07V35Y7M2
product_title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             10 pieces ring bottle opener stainless steel beer bottle opener colorful finger bottle opener for party family gift supplies
product_description                                                                                                                                                                                                                                                                                                                                     features  practical size every beautiful and practical ring bottle opener is only 22 mm 087 inches it fits on the finger very well which makes it easier to open the bottle portable and convenient to carry  sturdy material these ring bottle openers are made of quality stainless steel and they are extremely sturdy and durable they help you open every bottle faster and safer can last for a long time use  stylish design all ring bottle openers are designed to be very stylish keeping up with the trend of the times bright colors will make them more popular with everyone bring you good mood when using it  specifications material stainless steel color as pictures shown size 22 mm 087 inches  package includes 10 x ring bottle openers
product_bullet_point    practical size every beautiful and practical ring bottle opener is only 22 mm 087 inches it fits on the finger very well which makes it easier to open the bottle portable and convenient to carry\nsturdy material these ring bottle openers are made of quality stainless steel and they are extremely sturdy and durable they help you open every bottle faster and safer can last for a long time use\nrich variety there are five different colors ring bottle openers in each bag and each comes with two colors there are a wide variety of choices for you to choose from which is definitely enough for your daily life color as pictures shown\ndiverse usage you can use these ring bottle openers to open the bottles at the party or you can give them as a gift to your family or friends to better promote your relationship it will definitely be a very popular gift\nstylish design all ring bottle openers are designed to be very stylish keeping up with the trend of the times bright colors will make them more popular with everyone bring you good mood when using it
product_brand                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     boao
product_color                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        as pictures shown
query                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               bottle opener ring
esci_label                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           E
split                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            train
binary_label                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         1
Name: 100, dtype: object

In [41]:
df.iloc[recommended_products[0]]

,product_id,product_title,product_description,product_bullet_point,product_brand,product_color,query,esci_label,split,binary_label
28094,B089GYKNPL,2pcs fashion couple rings stainless ring steel rotatable bottle opener party ring creative versatile beer bottle openershipment from usa fast delivery blakslive 7,punk wedding mens stainless band ring spin titanium steel rotatable chain product description this is a cool chaintype rotating ring that can be used as a bottle opener you can perform magic tricks to open the beer smoothly at the party this is very enviable and very interesting but also makes us a party star stylish design exquisite fashion technical index material perfect titanium steel product weight 6g note due to the different display and lighting effects the actual color of the product may be slightly different from the color shown on the picture,fashion beer bottle openereasy to open the bottle it can make you in the party the field the bar the school and other gatherings with friends make you quick and quick beer bottle so you quickly become a friends eye magician give your friends a deep impression\nmade of highquality stainless steel durable the inside and surface are well polished and comfortable to wear it can withstand prolonged wear and tear\nthis ring has an inner ring that can be rotated manually and locked in the main chain this is a very interesting ring a stylish design suitable for everyday use and very suitable as a tool to relieve stress especially for manic or irritable people\nunique and fashionable designa meaningful way to share lovevery suitable for the gift selection of special occasions such as christmas valentines day birthday anniversary wedding very suitable for loversyou can also think of it as a friendship ring one for you and the other for your friends,na,blakslive,bottle opener ring,E,train,1
100,B07V35Y7M2,10 pieces ring bottle opener stainless steel beer bottle opener colorful finger bottle opener for party family gift supplies,features practical size every beautiful and practical ring bottle opener is only 22 mm 087 inches it fits on the finger very well which makes it easier to open the bottle portable and convenient to carry sturdy material these ring bottle openers are made of quality stainless steel and they are extremely sturdy and durable they help you open every bottle faster and safer can last for a long time use stylish design all ring bottle openers are designed to be very stylish keeping up with the trend of the times bright colors will make them more popular with everyone bring you good mood when using it specifications material stainless steel color as pictures shown size 22 mm 087 inches package includes 10 x ring bottle openers,practical size every beautiful and practical ring bottle opener is only 22 mm 087 inches it fits on the finger very well which makes it easier to open the bottle portable and convenient to carry\nsturdy material these ring bottle openers are made of quality stainless steel and they are extremely sturdy and durable they help you open every bottle faster and safer can last for a long time use\nrich variety there are five different colors ring bottle openers in each bag and each comes with two colors there are a wide variety of choices for you to choose from which is definitely enough for your daily life color as pictures shown\ndiverse usage you can use these ring bottle openers to open the bottles at the party or you can give them as a gift to your family or friends to better promote your relationship it will definitely be a very popular gift\nstylish design all ring bottle openers are designed to be very stylish keeping up with the trend of the times bright colors will make them more popular with everyone bring you good mood when using it,boao,as pictures shown,bottle opener ring,E,train,1
51588,B074FXTH6K,vqysko bottle opener ring bandbeer bar tool creative versatile stainless steel finger party ring silver 8,vqysko beer bar tool creative versatile stainless steel finger bottle opener ring party ring 100 brand new item and top quality never fade product quality guarantee reasonable pricesafety sale and delivery management including one black velvet bag suitable as a gift stainless steel jewellery it does not tarnish and oxidize which can last longer than other jewelries it is able to endure a lot of wear and tear such advantages make it a more popular accessory tuji jewelry we are the one of a jewelry global supplier integrating with the design production and sales mainly in stainless steel jewelry for many years supply different kinds of style in necklaces rings earrings bracelets and bangles the stores advantage high quality productsreasonable pricevariety styles of the newest fashion stainless steel jewelry,materialstainless steel\nsize6789101112 width8175mm\nweight8g\ncomfort fit designpackaged in a free velvet box\ngift suit forbirthdaychristmasvalentines dayweddingparty,vqysko,silver,bottle opener ring,E,train,1
23565,B07B9X2BLB,topgrillz 18mm 18k gold plated iced out cz lab diamond miami mens choker cuban link chain for women necklace hip hop18mm gold22,topgrillz cuban miami necklace this completely iced out necklace is made from a brass core plated with premium 14k gold plating it is flooded with zircon each micropave set by a professional jeweler jewelry care please avoid direct contact with water perspiration and chemicals such as perfume detergent and lotion excessive light heat or moisture will deteriorate the quality of the plating on the metal also exposing plated jewelry to liquids will cause the plating to lose its finish please take care to protect your bling as you would most jewelry,safe and environmental materials we electroplated the 18k gold and white gold for 6 times 03m over the environmental brass so it will not tarnish or fade for the bling stones each stone is carefully chosen for a 5a round cubic zirconia by a professional jewelry making team\ntrending design the iced cuban link chain is of popularity among hip hop fans which differs from the classical form of the chain less rounded and carefully worked out the double lock clasp is stable enough and can be adjusted easilythe double safety lock clasp is more stable to lock and will make the chains looks more exquisite\nstrict quality control we have our own quality control team who will examine the diamonds and polished parts of the items 360before shipping which ensures us dispatch the finest hip hop cuban link chains to our customers\ncollocate to show personalty for all occastion hip hop miami cuban link chains are an excellent accessory to hip hop fashion collocation and commonly wore by rappers like post malonemigos billie eilish lil pump and so on most people wear with other chains and pendants to get a shine and personalized especially suitable for halloween party hip hop fashion performance music concert daily wear birthday gift for those who are fond of hip hop fashion elements\nfabulous customer services we always try to get your satisfaction but there may be some force majeure inevitably which will let you have a bad shopping experience we hope that when therere anything wrong with our items please just leave us with a message were preparing to solve all the problem for you with high satisfaction,topgrillz,gold,ice necklace for men,E,train,1
50833,B07623YD7T,sterling silver personalized domed and hammered one name necklace customize with your choice of characters hammered finish includes 925 chain and swarovski birthstone gifts for her mother wife,ajs collection sterling silver personalized domed and hammered one name necklace is a clean and elegant accessory ideal for mothers it features one sterling silver disc 34 inch diameter personalized with a custom name the charm is hammered by hand for a unique look and hung together with your choice of swarovski birthstone comes with a choice of sterling silver cable box or ball chain features 34 inch round sterling silver disc 15 character limit 1 swarovski birthstones choice of 16 18 20 22or 24 sterling silver cable box or ball chain ready to gift comes inside an environmentally responsible recycled gift box with a organza bag and handtied bow it is ready to gift asis or if you would like a more fancier look we offer a premium gift box click add gift options during checkout who is this for this necklace will make the perfect gift for a wife a girlfriend a grandmother a new mom best friend or a significant other and will make a sweet and memorable gift for many different occasions such as an anniversary gift birthday gift mothers day gift christmas gift or even just an everyday gift also makes a great gift for best friends and even makes a perfect gift for yourself,personalized jewlery this pendant necklace is custommade for you with the names of your choice\nincludes chain this personalized treasure come with a 925 chain type and length of your choice\nperfect quality all our necklaces are made in the usa and using only the finest quality material such as sterling silver available focusing on style quality and uncompromising attention to detail\nperfect gift this personalized necklace is a great gift for your mother grandmother wife girlfriend loved one or a special treat for yourself\nfast shipping we will ship within 24 business hours and often times the same day,ajs collection,silver,birthstone necklace for mothers,E,test,1

In [22]:
torch.rand(1,768).view(-1,768).shape

torch.Size([1, 768])

# query tower inference

In [3]:
import requests
import torch

url = "http://localhost:5001/invocations"

input_tensor = torch.rand(1,768)

# Convert to list
data = {"inputs": input_tensor.tolist()}

# Send request
response = requests.post(url, json=data)

# Print prediction
print(response.json())

{'predictions': [[-0.12178698182106018, 0.3475428819656372, -0.0008688937523402274, 0.003265833016484976, 0.17057190835475922, 0.19004526734352112, -0.13434579968452454, -0.1344868391752243, -0.019446058198809624, 0.05593753978610039, 0.11845600605010986, 0.35243669152259827, -0.08282971382141113, 0.14524118602275848, -0.348490446805954, 0.0861508697271347, -0.03892110288143158, -0.16809740662574768, 0.0006604751106351614, -0.08071773499250412, -0.032925426959991455, -0.35876038670539856, -0.17257872223854065, 0.2554073929786682, -0.08478299528360367, -0.07180222868919373, 0.04382268339395523, 0.34291860461235046, -0.03623281419277191, -0.1698543280363083, 0.023454593494534492, -0.20194444060325623]]}

In [4]:
response.json()['predictions']

[[-0.12178698182106018,
  0.3475428819656372,
  -0.0008688937523402274,
  0.003265833016484976,
  0.17057190835475922,
  0.19004526734352112,
  -0.13434579968452454,
  -0.1344868391752243,
  -0.019446058198809624,
  0.05593753978610039,
  0.11845600605010986,
  0.35243669152259827,
  -0.08282971382141113,
  0.14524118602275848,
  -0.348490446805954,
  0.0861508697271347,
  -0.03892110288143158,
  -0.16809740662574768,
  0.0006604751106351614,
  -0.08071773499250412,
  -0.032925426959991455,
  -0.35876038670539856,
  -0.17257872223854065,
  0.2554073929786682,
  -0.08478299528360367,
  -0.07180222868919373,
  0.04382268339395523,
  0.34291860461235046,
  -0.03623281419277191,
  -0.1698543280363083,
  0.023454593494534492,
  -0.20194444060325623]]

# embedding model inference

In [16]:
import requests
import torch

url = "http://localhost:5001/invocations"

input_tensor = torch.rand(1,768)

# Convert to list
data = {"inputs": ['bottle opener ring'],
        }

# Send request
response = requests.post(url, json=data)

# Print prediction
print(response.json())

{'predictions': [[-0.04666038602590561, 0.05391041934490204, 0.020811129361391068, 0.0009996165754273534, 0.1019439697265625, -0.04832988232374191, -0.02423499897122383, -0.019809257239103317, 0.07352948933839798, -0.017443235963582993, -0.06511249393224716, 0.01288723573088646, -0.07214204221963882, 0.03678182512521744, -0.07344791293144226, 0.060947973281145096, 0.03496871516108513, -0.03130273148417473, 0.042264603078365326, 0.07275903224945068, 0.08825119584798813, 0.029291311278939247, 0.05080761760473251, -0.07254785299301147, -0.04930812120437622, 0.10655299574136734, 0.020048774778842926, -0.043175939470529556, -0.04609251767396927, -0.023546215146780014, -0.02543213590979576, -0.0632701888680458, -0.03787185251712799, -0.010317663662135601, 0.10689179599285126, 0.030998487025499344, 0.022398168221116066, 0.02829151600599289, -0.04349838197231293, 0.034068141132593155, -0.0342831127345562, -0.016605820506811142, 0.0422082357108593, -0.01491609774529934, -0.04781549423933029, 0.03981880098581314, -0.08439426124095917, 0.015092668123543262, -0.04154042899608612, 0.015632575377821922, -0.04180573672056198, 0.04500475898385048, -0.013335139490664005, -0.003579634241759777, 0.004181818105280399, 0.05298899859189987, -0.04930924251675606, 0.05476797744631767, 0.07308778911828995, 0.024910997599363327, 0.08841930329799652, -0.004219733644276857, -0.01397881843149662, -0.034244026988744736, -0.03436369448900223, -0.03855324164032936, 0.0360788069665432, -0.05700291320681572, 0.1535240113735199, 0.06856226921081543, -0.012831579893827438, 0.01583712548017502, 0.0027460798155516386, 0.035085227340459824, 0.026553770527243614, 0.030098678544163704, -0.0510246641933918, 0.02606184221804142, -0.04714186489582062, 0.016444887965917587, -0.022661447525024414, -0.027725636959075928, 0.05305967852473259, 0.012719649821519852, 0.000911257928237319, -0.04416859522461891, 0.020996781066060066, 0.03464281186461449, -0.00706130126491189, 0.02085079438984394, 0.011612433940172195, 0.03821872919797897, 0.026419876143336296, -0.0668369010090828, 0.030581403523683548, 0.0396970696747303, -0.02041817456483841, -0.006082052830606699, 0.07640095800161362, 0.03149629756808281, 0.042985837906599045, 0.06310001760721207, 0.0558227114379406, -0.035243187099695206, 0.018208147957921028, -0.05983094125986099, -0.001323467819020152, -0.07473758608102798, 0.001206454006023705, 0.015253033488988876, 0.01684979349374771, -0.06675681471824646, -0.020588982850313187, -0.031006982550024986, -0.02074543759226799, -0.05857984721660614, 0.030237043276429176, -0.005602543242275715, 0.0177762508392334, 0.026936626061797142, -0.021887414157390594, 0.01050297450274229, 0.004444730002433062, -0.021020838990807533, -0.06439508497714996, -0.013475294224917889, -0.011120866984128952, -0.07173242419958115, -0.01751360483467579, -0.04388941079378128, 0.0235803984105587, 2.0715739083243534e-05, 0.04128063842654228, -0.05909818783402443, 0.044283170253038406, -0.0007756544509902596, 0.023508401587605476, 0.11528415977954865, 0.0055406950414180756, -0.002304556779563427, -0.06827209889888763, -0.046265967190265656, -0.06569518893957138, 0.040243491530418396, 0.005745780188590288, 0.0006144330254755914, -0.06829588860273361, 0.022936450317502022, -0.015928147360682487, 0.015095130540430546, -0.048284195363521576, 0.001978316344320774, 0.027007978409528732, -0.0168328694999218, 0.0007134919869713485, 0.01639672927558422, 0.0004791637766174972, 0.002024674555286765, -0.049763232469558716, -0.01924627646803856, 0.002226779004558921, -0.016503451392054558, -0.008426333777606487, -0.027325373142957687, 0.012925873510539532, -0.012581966817378998, 0.017609786242246628, -0.01713344268500805, 0.045807112008333206, 0.014819140546023846, -0.05337484925985336, -0.005764054600149393, 0.02835480310022831, 0.0005032101180404425, -0.030692627653479576, 0.013812337070703506, 0.0030080857686698437, 0.06760887801647186, -0.07011164724826813, 0.03579806163907051, -0.00034592123120091856, -0.012836746871471405, -0.04405646771192551, -0.06462543457746506, 0.02079491876065731, -0.0025867631193250418, 0.03956564888358116, -0.04305897280573845, -0.029238244518637657, 0.00867526140064001, -0.03580627590417862, -0.045259978622198105, -0.06722165644168854, 0.03127192705869675, -0.03203291818499565, -0.017931105569005013, -0.025355663150548935, -0.012646605260670185, -0.007969836704432964, 0.038679759949445724, 0.083206407725811, -0.0006876155384816229, -0.018413282930850983, -9.52301052166149e-05, 0.0029828182887285948, -0.016402143985033035, -0.05829150229692459, -0.03469734638929367, -0.06279563903808594, -0.0381445474922657, 0.057262200862169266, 0.06952214241027832, 0.012707065790891647, 0.038663145154714584, -0.030265983194112778, -0.047265514731407166, 0.015079367905855179, -0.012318301014602184, 0.02969139814376831, -0.04557505249977112, -0.02982746623456478, -0.03434044122695923, -0.013108514249324799, -0.0135282501578331, 0.054389312863349915, 0.012140721082687378, -0.04518566653132439, 0.0394660085439682, -0.012353837490081787, 0.026602083817124367, 0.06017041951417923, 0.0059843603521585464, 0.02893996611237526, -0.02504676766693592, -0.035574935376644135, 0.002607739297673106, -0.004137167241424322, -0.012461962178349495, -0.07330265641212463, 0.03610370308160782, 0.02971082367002964, 0.029296254739165306, 0.008827906101942062, 0.01573268696665764, 0.022593842819333076, 0.024017242714762688, -0.0631122961640358, -0.048366907984018326, -0.03504364192485809, -0.021853836253285408, -0.0127674899995327, 0.002432375680655241, -0.02533598616719246, 0.03995054215192795, -0.026041073724627495, -0.0332740843296051, 0.039238542318344116, 0.01678629033267498, 0.02292029745876789, -0.05393499508500099, 0.023197365924715996, -0.009075271897017956, -0.014988849870860577, 0.0014885083073750138, -0.0011666418286040425, -0.062028635293245316, 0.03227360174059868, -0.03996273875236511, 0.026750892400741577, -0.007459874264895916, 0.021235141903162003, -0.0001779442245606333, 0.005852635484188795, 0.021708857268095016, -0.01907965913414955, 0.001675498322583735, 0.025171933695673943, -0.007152102887630463, -0.02406405098736286, 0.011432136408984661, -0.015329493209719658, -0.025603918358683586, -0.030578289180994034, -0.05121948570013046, -0.009918139316141605, -0.012371035292744637, 0.002562680747359991, -0.052420444786548615, 0.03559543564915657, 0.03545961529016495, -0.019138198345899582, -0.05265378952026367, -0.025539889931678772, -0.0005316863534972072, 0.01809804141521454, 0.06974545866250992, -0.06264783442020416, 0.041383493691682816, 0.011808577924966812, 0.01511570904403925, 0.0032349592074751854, -0.021327298134565353, 0.010208726860582829, -0.021621834486722946, 0.012037476524710655, 0.006683737970888615, -0.06469594687223434, -0.04926634579896927, -0.026556221768260002, -0.017823297530412674, 0.02739039622247219, 0.03581475466489792, -0.019821450114250183, -0.01842600852251053, -0.010201863013207912, 0.0003189606941305101, 0.015455132350325584, 0.032037537544965744, -0.030296748504042625, -0.017713554203510284, -0.008215189911425114, 0.0965934619307518, -0.00025937845930457115, 0.04608873650431633, -0.013506539165973663, -0.0062340013682842255, 0.06556293368339539, 0.02368367463350296, -0.02118907868862152, -0.016889238730072975, -0.0045909639447927475, 0.015425306744873524, 0.009860525839030743, -0.07016415148973465, 0.029100263491272926, 0.017836276441812515, 0.04768836870789528, -0.0021812906488776207, 0.014157569967210293, 0.01631029136478901, -0.03097756952047348, 0.0035732791293412447, -0.0089150071144104, 0.05208875611424446, -0.0276082381606102, -0.023357484489679337, -0.003400900401175022, -0.059962887316942215, 0.03242218866944313, -0.01969149149954319, -0.012558285146951675, 0.03367745131254196, 0.023143839091062546, 0.05568677559494972, 0.033746715635061264, 0.008848574943840504, 0.011036342941224575, 0.0308059174567461, -0.017461173236370087, 0.00808872003108263, 0.005904219578951597, -0.01927044242620468, 0.050932351499795914, -0.007905676029622555, -0.015892699360847473, -0.0012353732017800212, -0.03615795075893402, 0.023292623460292816, -0.02961430698633194, 0.0927160233259201, -0.038689520210027695, 0.04969588667154312, 0.02656928449869156, 0.03199838101863861, -0.012138593941926956, 0.008532686159014702, -0.009652569890022278, 0.0031719801481813192, 0.04587006941437721, -0.025237692520022392, 0.01414435263723135, -0.008727800101041794, -0.013419009745121002, -0.02236638031899929, 0.020274827256798744, -0.04388589411973953, -0.014686714857816696, 0.03790706396102905, -0.02176903933286667, -0.01274673268198967, -0.0685790479183197, -0.026426687836647034, 0.03148385509848595, 0.034791018813848495, 0.048455074429512024, -0.04049566388130188, -0.004204327706247568, 0.06957755237817764, -0.043907035142183304, 0.01788761094212532, 0.028835924342274666, 0.029067877680063248, 0.006944648455828428, 0.05901262164115906, 0.004555544815957546, -0.00247974437661469, 0.07457159459590912, -0.08360923081636429, 0.0006225208635441959, 0.03602078557014465, 0.007238336838781834, -0.05584898963570595, 0.008710362017154694, -0.03016885183751583, 0.017671119421720505, -0.03750178962945938, 0.018679354339838028, -0.0012786962324753404, 0.15281756222248077, -0.003175888443365693, 0.015144549310207367, 0.055736131966114044, 0.020441217347979546, -0.04162000119686127, -0.011104771867394447, 0.07544614374637604, 0.03770192712545395, 0.03646594658493996, -0.029728684574365616, 0.044298309832811356, 0.004706929437816143, -0.024717794731259346, -0.04849999397993088, -0.04898950085043907, -0.05918896570801735, -0.05503099411725998, -0.021393951028585434, 0.0034881685860455036, 0.024418940767645836, -0.019942525774240494, 0.02391405776143074, 0.013971825130283833, 0.021759280934929848, -0.0663345530629158, 0.014192706905305386, 0.0020245981868356466, 0.03279019147157669, 0.0328194834291935, -0.013458608649671078, 0.013812934048473835, 0.0001295006222790107, 0.04811156168580055, -0.021383602172136307, -0.02043289691209793, 0.049091435968875885, -0.00707295211032033, -0.0004390209214761853, -0.010488824918866158, -0.01810353621840477, -0.05491010099649429, -0.02905583195388317, -0.02092709206044674, 0.02752004936337471, -0.03817856311798096, 0.07080892473459244, -0.0009236783371306956, 0.00263022817671299, 0.02643420733511448, 0.012674042955040932, 0.032171621918678284, 0.03750050812959671, -0.01963917724788189, -0.002733368193730712, 0.0028022273909300566, -0.026021813973784447, 0.04780472069978714, -0.028822636231780052, 0.051957257091999054, -0.03223777934908867, -0.03367431461811066, 0.05072103068232536, -0.00011584247113205492, 0.00780639098957181, -0.025513608008623123, 0.020683491602540016, 0.013514350168406963, -0.04243246838450432, -0.04593966156244278, 0.024085884913802147, 0.041442543268203735, -0.015197519212961197, 0.046552613377571106, -0.01888689026236534, -0.022766828536987305, 0.024864831939339638, 0.008471704088151455, 0.017707226797938347, -0.04711939021945, 0.06826115399599075, 0.023282183334231377, -0.030504673719406128, 0.0052255443297326565, -0.012985743582248688, -0.0013321569422259927, 0.04904521629214287, -0.0037202422972768545, -0.022553522139787674, 0.01810345984995365, 0.012721535749733448, 0.0013556539779528975, -0.045776791870594025, -0.01960679516196251, 0.018892765045166016, 0.04863017424941063, -0.002436181763187051, 0.02405617944896221, -0.012287252582609653, 0.05428951978683472, 0.0014637523563578725, 0.02293986827135086, 0.02568989247083664, 0.025625968351960182, -0.0006639697239734232, 0.016258345916867256, 0.013783476315438747, -0.023153802379965782, -0.011110940016806126, 0.0262604933232069, 0.007444789633154869, -0.05916280299425125, 0.009815328754484653, 0.06710654497146606, 0.03868088498711586, -0.03336566686630249, 0.009207360446453094, 0.05014108121395111, 0.004087693057954311, 0.012158744037151337, 0.018053021281957626, 0.011157450266182423, -0.09183693677186966, -0.030322907492518425, 0.04857032001018524, 0.024975283071398735, -0.016508053988218307, 0.013504606671631336, 0.001353594707325101, -0.03201105445623398, -0.03685725852847099, -0.008672057650983334, -0.045245472341775894, 0.046352505683898926, -0.0007713570375926793, 0.06735770404338837, 0.02464471198618412, -0.005269642453640699, -0.013080012984573841, -0.02833639457821846, -0.006026386748999357, 0.015253107994794846, -0.01641383394598961, -0.004185435362160206, 0.029315270483493805, -0.05006537213921547, -0.03152976557612419, 0.03781072050333023, 0.0009037652052938938, -0.007502530701458454, 0.06572840362787247, 0.008208767510950565, 0.03675146400928497, 0.0005811735172756016, 0.07540011405944824, -0.07288399338722229, -0.032170750200748444, -0.01399974524974823, -0.011652813293039799, -0.004537544678896666, -0.019838817417621613, 0.03332064673304558, -0.013115602545440197, -0.021367615088820457, 0.0170897226780653, 0.00483306311070919, -0.0016383251640945673, 0.007342000491917133, 0.03941499814391136, 0.034744031727313995, 0.024777019396424294, -0.021076509729027748, -0.0055170562118291855, 0.025396021082997322, -0.007195378188043833, -0.02069130726158619, -0.02953907661139965, -0.01756291463971138, 0.02289833314716816, -0.040011215955019, 0.037956684827804565, -6.224201206350699e-05, 0.0035452020820230246, -0.029665693640708923, 0.057985056191682816, -0.06977111846208572, 0.005619187839329243, 0.058532632887363434, -0.00862712599337101, -0.041902683675289154, -0.023195086047053337, 0.022368207573890686, 0.005907494109123945, -0.0006156110321171582, 0.040459632873535156, 0.02328377589583397, -0.042096175253391266, 0.019188251346349716, -0.037038493901491165, -0.002386939013376832, -0.031423233449459076, 0.00990809965878725, -0.013336623087525368, -0.001233908929862082, -0.01266452856361866, 0.03677010536193848, 0.014684312976896763, -0.003514231415465474, -0.027207372710108757, -0.0485280379652977, -0.07297415286302567, -0.011581034399569035, -0.019791727885603905, -0.026425423100590706, 0.009220869280397892, 0.010291538201272488, -0.025072472169995308, 0.0350998155772686, -0.037482377141714096, 0.019958902150392532, 0.020737094804644585, 0.014391348697245121, -0.0050609419122338295, 0.03652430698275566, -0.021514538675546646, -0.07535210996866226, 0.008683965541422367, 0.039727456867694855, 0.01538807898759842, 0.0326596237719059, -0.007474691607058048, 0.003064380493015051, 0.01791808381676674, -0.058056727051734924, 0.006524408236145973, -0.0166220311075449, -0.021261896938085556, -2.512203536753077e-05, -0.02129768580198288, -0.05169858783483505, 0.05291242152452469, 0.09231259673833847, 0.0009793223580345511, 0.03084143064916134, 0.003981634043157101, 0.03778694197535515, -0.046329595148563385, 0.03566180542111397, 0.010954503901302814, 0.030461981892585754, 0.02304348163306713, -0.046850018203258514, -0.0038865262176841497, -0.027908187359571457, 8.802755473880097e-05, -0.015638690441846848, -0.10257498174905777, -0.018390286713838577, 0.042831361293792725, -0.03175458684563637, -0.0230751670897007, 0.0166451595723629, -0.0531100332736969, 0.018475636839866638, -0.01881335861980915, 0.003681354923173785, -0.10090234875679016, -0.017808839678764343, 0.028594806790351868, -0.015678368508815765, 0.02137371525168419, 0.007329917512834072, -0.004191863350570202, -0.003649680409580469, 0.03288588300347328, 0.01211926992982626, 0.02985691837966442, -0.029410304501652718, 0.0374518521130085, 0.023533595725893974, 0.04671227186918259, 0.017445825040340424, -0.015859967097640038, -0.010102422907948494, 0.013465029187500477, 0.0036831728648394346, 0.024161117151379585, -0.019429488107562065, -0.013024694286286831, -0.012433950789272785, 0.018977846950292587, -0.015267560258507729, 0.06509841233491898, 0.043135810643434525, 0.011996442452073097, 0.07638008892536163, -0.013580932281911373, -0.04187267646193504, -0.061287492513656616, 0.05097294971346855, 0.0415838286280632, 0.07711514830589294, -0.04948296397924423, 0.030597833916544914, -0.006161173339933157, 0.029022855684161186, -0.022171886637806892, -0.01565231755375862, 0.01048367377370596, 0.0053101335652172565, -0.06464952230453491, 0.025421565398573875, -0.031124219298362732, 0.08925148844718933, -0.0023822453804314137, 0.003564384300261736, 0.008578600361943245, 0.02064032107591629, 0.06805349886417389, 0.008611694909632206, 0.01181120052933693, -0.01962081529200077, 0.014954747632145882, -0.02256615087389946, 0.01645703800022602, 0.02887779287993908, 0.009467159397900105, -0.05547573044896126, 0.021125217899680138, 0.04863276705145836, -0.012059727683663368, -0.0022837258875370026, -0.01239082682877779, 0.02803218737244606, 0.02187294512987137, 0.027779461815953255, 0.015757696703076363, 0.00433755898848176, -0.0013086338294669986, -0.028142336755990982, -0.031047534197568893, 0.010174207389354706, 0.03508729115128517, -0.006480605807155371, 0.03448324650526047, 5.179645449970849e-05, -0.025538166984915733, 0.015370851382613182, 0.020075766369700432, -0.006818112917244434]]}

In [4]:
! pwd

/home/linuxachin/Desktop/Codes/Two-Tower-Recommendation/notebook

In [2]:
import sys
import os

# Add the project directory (parent of notebook and scripts) to sys.path
project_path = os.path.abspath(os.path.join(os.getcwd(), ".."))
if project_path not in sys.path:
    sys.path.append(project_path)

# # Now you can import modules from scripts
# import scripts.my_script  # Import a specific script

In [9]:
from scripts import get_embedding, get_tower_embedding, index_search
# import get_embedding

query = "bottle opener"

# print(name)

query_tower_url = "http://localhost:5001/invocations"
embedding_model_url = "http://localhost:5002/invocations"


q_embedding = get_embedding.get_embedding_from_model(query,embedding_model_url)
q_tower_embedding = get_tower_embedding.get_query_tower_embedding(q_embedding,query_tower_url)
recommendations = index_search.retrieve_products(q_tower_embedding,index_path='../assets/product_tower_embedding.index',top_k=10)

In [10]:
recommendations

,product_title,product_description,product_brand
47456,gacube bartender bottle openersstainless steel heavy duty beer bottle openers orange,gacube bartender bottle openersstainless steel heavy duty beer bottle openers orange,gacube
82428,rommeka bottle can and jar grip opener multi function 4in1 5in1 and 6in1 kitchen tools set anti slip lid seal remover easy twist off for children elderly arthritic and weak hand pack of 3,rommeka bottle can and jar opener you dont need to ask for help with this convenient kitchen gadgets and save your hands from the pain and stress these multi opening tools are practical and lightweight can be carry to anywhere also very easy to use idea for family gathering colleagues gathering bbq picnic and so on best gift for family or friends 4in1 jarlid opener 4 different size opener allows you gauge any lid or cap size choose appropriate opener size and twist off slipping or breakage 5in1 bottle opener popular handy device for safe opening cans with ring release vacuum on jar lids open any can jar or bottle with minimum effort this tool is great for opening those water bottles that have short tops that are hard to grip easily twist off screw caps with a simple twist 6in1 sode can opener easy tearing pulling turning and twisting for anything you crave open pop tabs pull tabs bags safety seals metal and plastic bottle caps jars and more with to no efforts tips please avoid exposing the jar opener to direct sunlight for fear the rubber aging package included 1 x 4in1 jar opener 1 x 5in1 bottle opener 1 x 6in1 can opener,rommeka
47359,ahumans bottle opener hammer of thor shaped bottle opener abs marvel beer opener golden silvery gold,ahumans bottle opener hammer of thor shaped bottle opener abs marvel beer opener gold silvery specification color golden silvery size 1657047mm649276185 inches material abs metal usage scenarios home bars restaurants hotels party venue bbq package included 1bottle opener customer service our customer service team will try their best to help all the buyers deal with various kinds of issues in 24 hours please contact them first via seller platform email if you have any questions,ahumans
92658,3 packs drincarier waiters corkscrew professional wine openersupgraded heavy duty stainless steel wine keyclassic allinone corkscrew bottle opener and foil cutter 3pack pink,drincarier teflon waiters corkscrew is a classic corkscrew design that has a foil cutter blade a two stage cork lifter and bottle opener open a wine bottle by twisting in the screw placing the openers shortest step on the top of the bottle lip and pivoting up the handle after raising the cork partially lower the handle to engage the longest opener step on the bottle lip then pivot on the handle to remove the cork from the bottlesmall and easy to carry after folded you can take it anywhere for enjoying wine when campinghiking or travelingperfect for serverssommeliersbartenders and daily needs in home,drincarier
34959,key bottle openers assorted vintage skeleton keys wedding party favors pack of 70 silver,package include 70 pieces vintage key bottle openers assorted antique silver skeleton keys 10 pieces each style 7 styles quality design look and feel each is made of sturdy quality metal alloy and has an antiqued color finish to give them a beautiful vintage look the keys measure between 275 35 inches long,xonor
31295,nidavellir 2pack mjolnir keychain bottle opener thor hammer bottle opener keychain thor keychain beer bottle opener silver bronze,thors hammer keychain bottle opener forged in the heart of a dying star its power has no equal as a weapon to destroy or as a tool to build it is fit companion for a king but im just used to open the beer excellent features thor keychains made of highquality zinc alloy and double polished for a shiny rustproof and breakresistant surface cool beer bottle opener keychain with exquisite workmanship looks terrific and high end great novelty for using in parties creative and stunning design this thor key chain can also be used as a decoration for home study office perfect gifts for any beer lovers specifications material metal alloy size 3 x 13 inches item weight 2 ounces package content1 x silver hammer bottle opener keychain1 x bronze hammer bottle opener keychain,nidavellir
39645,nidavellir mjolnir bottle opener thor hammer bottle opener thor beer bottle opener with bronze mjolnir keychain bottle opener,mjolnir hammer beer bottle opener forged in the heart of a dying star its power has no equal as a weapon to destroy or as a tool to build it is fit companion for a king but im just used to open the beer excellent features thor opener made of premium abs resin and stainless steel durable and breakresistant thors hammer keychain bottle opener made of highquality zinc alloy and double polished for a shiny rustproof and breakresistant surface nice hammer opener and thor key chain with exquisite workmanship look terrific and high end solid enough to crack walnuts and can be the selfprotection tool when you walk in dark alone great novelty for using in parties creative and stunning design these mjolnir hammer bottle opener thor keychains can also be used as decorations for party hotel home or used as bar gadgets perfect gifts for any beer lovers specifications material hammer bottle opener abs resin metal only opener part hammer keychain bottle opener zinc alloy size weight hammer bottle opener 65 x 28 inches 48 ounces hammer keychain bottle opener 3 x 13 inches 2 ounces package content1 x silver hammer bottle opener1 x bronze hammer bottle opener keychain,nidavellir
85436,7piece cocktail shaker set bar tools stainless steel cocktail shaker set bartender kit with all bar accessories cocktail strainer double jigger bar spoon bottle opener pour spouts,bar set,finedine
53532,magnetic bottle opener thor hammer bottle opener fridge magnet beer bottle opener gifts for men husband dad boyfriend amjudot,specification namerefrigerator magnetic hammer of thor shaped beer bottle opener materialthe magnetic bottle opener is made of abs metal product size approx 165x7x45cm65x28x18inch mesure by the biggest point colorthe color of the thor bottle opener are silver and gold for option function with the 3d thor of hammer bottle opener you can easily open the bottle lid within seconds without any mess or spilling even when using one hand no longer struggle to open caps anymore just extremely simple to use applied occation the magnetic bottle opener can be apply on home bars restaurants hotelsparty venue bbqif you want you can take it out for a outside partiesit is light body have small size will not be the burden of your backpack packing quantity1 x bottle opener note all dimensions are measured manually and there may be small deviations we guarantee to provide the best quality products and best service if any problems you can contact us we will provide a variety of solutions for you to choose,amjudot
51278,professional wine openerbest bottle opener for beer or wine allinone waiters corkscrewthe favored choice of sommeliers waiters and bartenders around the world10packs,10 pack threeinone bottle opener made from premium thick stainless steel folding beer wine opener serrated foil cutter color black the product is made from allmetal structure very sturty and durable stainless steel serrated blade and double hinged support its perfect for bottles of wine or beer cans etcand even can be used in different lengths of corks especially for bars restaurants and families camping etc cheap price easy to use easy to carry,qc style